# wranger.toml
name = "git-forest-api"
main = "src/index.ts"
compatibility_date = "2026-02-16"
workers_dev = false

[[routes]]
pattern = "forest.dliv.gg"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "git-forest-version-check"
database_id = "28dbcad0-a42c-4a7d-bb9a-aebf335adff5"

[vars]
LATEST_VERSION_STABLE = "0.3.1"
LATEST_VERSION_BETA = "0.2.18-beta.4"
